# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.2
	loader_version=0.19.3

# Mod Properties
	mod_version = 1.2.2
	maven_group = de.fisch37
	archives_base_name = BetterServerPacksFabric

# Dependencies
	lowest_mc_version=26.2
	next_incompatible_mc_version=26.3
	fabric_version=0.154.0+26.2
	config_version=2.1.0
