# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.1
	loader_version=0.17.3

# Mod Properties
	mod_version = 1.2.1
	maven_group = de.fisch37
	archives_base_name = BetterServerPacksFabric

# Dependencies
	lowest_mc_version=26.1
	next_incompatible_mc_version=26.2
	fabric_version=0.144.0+26.1
	config_version=2.0.1
